//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FabrykaNotatek
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBNotatkiEntities5 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBNotatkiEntities5 object using the connection string found in the 'DBNotatkiEntities5' section of the application configuration file.
        /// </summary>
        public DBNotatkiEntities5() : base("name=DBNotatkiEntities5", "DBNotatkiEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBNotatkiEntities5 object.
        /// </summary>
        public DBNotatkiEntities5(string connectionString) : base(connectionString, "DBNotatkiEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBNotatkiEntities5 object.
        /// </summary>
        public DBNotatkiEntities5(EntityConnection connection) : base(connection, "DBNotatkiEntities5")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NotatkaEncja> NotatkaEncjas
        {
            get
            {
                if ((_NotatkaEncjas == null))
                {
                    _NotatkaEncjas = base.CreateObjectSet<NotatkaEncja>("NotatkaEncjas");
                }
                return _NotatkaEncjas;
            }
        }
        private ObjectSet<NotatkaEncja> _NotatkaEncjas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NotatkaEncjas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotatkaEncjas(NotatkaEncja notatkaEncja)
        {
            base.AddObject("NotatkaEncjas", notatkaEncja);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNotatkiModel", Name="NotatkaEncja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NotatkaEncja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NotatkaEncja object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static NotatkaEncja CreateNotatkaEncja(global::System.Guid id)
        {
            NotatkaEncja notatkaEncja = new NotatkaEncja();
            notatkaEncja.id = id;
            return notatkaEncja;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataUtworzenia
        {
            get
            {
                return _dataUtworzenia;
            }
            set
            {
                OndataUtworzeniaChanging(value);
                ReportPropertyChanging("dataUtworzenia");
                _dataUtworzenia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataUtworzenia");
                OndataUtworzeniaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataUtworzenia;
        partial void OndataUtworzeniaChanging(Nullable<global::System.DateTime> value);
        partial void OndataUtworzeniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataModyfikacji
        {
            get
            {
                return _dataModyfikacji;
            }
            set
            {
                OndataModyfikacjiChanging(value);
                ReportPropertyChanging("dataModyfikacji");
                _dataModyfikacji = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataModyfikacji");
                OndataModyfikacjiChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataModyfikacji;
        partial void OndataModyfikacjiChanging(Nullable<global::System.DateTime> value);
        partial void OndataModyfikacjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notatka
        {
            get
            {
                return _notatka;
            }
            set
            {
                OnnotatkaChanging(value);
                ReportPropertyChanging("notatka");
                _notatka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notatka");
                OnnotatkaChanged();
            }
        }
        private global::System.String _notatka;
        partial void OnnotatkaChanging(global::System.String value);
        partial void OnnotatkaChanged();

        #endregion

    
    }

    #endregion

    
}
